# Generated by Django 4.1.2 on 2022-10-18 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='regions_city',
            field=models.TextField(verbose_name='regions_city'),
        ),
    ]
