# Generated by Django 4.1.2 on 2022-10-18 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_task_regions_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='country',
            field=models.CharField(max_length=200, verbose_name='country'),
        ),
    ]
